# Generated by Django 3.2.4 on 2021-06-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
    ]
