# Generated by Django 3.2.4 on 2021-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='viewer',
        ),
        migrations.AddField(
            model_name='question',
            name='viewer',
            field=models.ManyToManyField(null=True, to='polls.Viewer'),
        ),
    ]
